Include workflow badges
mensatt/backend pull request #79
Opened 2022-07-21 21:40 UTC by stormofice

2022-07-21 21:44 UTC, StealWonders approved these changes

2022-07-21 22:00 UTC, tobiges commented on .github/workflows/deploy-main-in-dev-env.yml
> +name: Deployment
Would name it Build & Deploy dev api

2022-07-21 22:31 UTC, StealWonders commented on .github/workflows/deploy-main-in-dev-env.yml
> +name: Deployment
Development Deployment

2022-07-21 22:33 UTC, StealWonders requested changes

2022-07-21 22:33 UTC, StealWonders commented on README.md
> +[![Build & Deploy](https://github.com/mensatt/backend/actions/workflows/go.yml/badge.svg)](https://github.com/mensatt/backend/actions/workflows/go.yml)
Build & Test

2022-07-21 22:33 UTC, StealWonders commented on README.md
> +[![Deployment](https://github.com/mensatt/backend/actions/workflows/deploy-main-in-dev-env.yml/badge.svg)](https://github.com/mensatt/backend/actions/workflows/deploy-main-in-dev-env.yml)
Development Deployment

2022-07-24 22:12 UTC, tobiges approved these changes

2022-07-24 22:13 UTC, merged